- name: Rename APK to EUB39B
        run: |
          mv app/build/outputs/apk/release/*.apk app/build/outputs/apk/release/EUB39B.apk || true
          mv app/build/outputs/apk/debug/*.apk app/build/outputs/apk/debug/EUB39B.apk || true

      - name: Upload APK to Latest Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "EUB 39 Batch Latest Build"
          files: |
            app/build/outputs/apk/release/EUB39B.apk
            app/build/outputs/apk/debug/EUB39B.apk
