name: Android Build

on:
permissions:
  contents: write
  workflow_dispatch:
  push:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Rename APK with Version
        run: |
          mv app/build/outputs/apk/debug/*.apk app/build/outputs/apk/debug/EUB39B_v1.0.${{ github.run_number }}.apk || true

      - name: Upload APK to Latest Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "EUB 39 Batch Latest Build v1.0.${{ github.run_number }}"
          files: |
            app/build/outputs/apk/debug/EUB39B_v1.0.${{ github.run_number }}.apk
